package com.example.demo2.model;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Random;
import java.util.Set;

/**
 * Logic model for a 6x6 sudoku board game.
 *
 * <p>This class only manages intern sudoku logic, does not have any FXML elements
 or view utilities.</p>
 *
 * <p>Board structure is:</p>
 * <ul>
 *     <li>6 rows/li>
 *     <li>6 columns</li>
 *     <li>6 2×3 block</li>
 *     <li>Valid numbers: from 1 to 6</li>
 * </ul>
 *
 * <p>Game data is stored on the following structures {@link HashMap} and {@link HashSet}:</p>
 * <ul>
 *     <li>{@code board}: map {@code "fila,columna"} → Actual number</li>
 *     <li>{@code solution}: map {@code "fila,columna"} → Sudoku Answer</li>
 *     <li>{@code fixedCells}: Theese are the cells that can not be changed</li>
 * </ul>
 *
 * <p>an empty cell <strong>does not</strong> exist on the map {@code board},
 * so it is not needed a trash value {@code 0}.</p>
 *
 * @author Santiago Torres
 * @version 2.0
 */
public class SudokuBoard {

    /** Board size (6x6). */
    private static final int SIZE = 6;

    /** Rows number peer block. */
    private static final int BLOCK_ROWS = 2;

    /** clumns number peer block */
    private static final int BLOCK_COLS = 3;

    /**
     * Actual state of board.
     *
     * <p>Key: {@code "row,column"} — Value: number placed (1–6).
     * If a key does not exist, the cell is empty</p>
     */
    private Map<String, Integer> board;

    /**
     * Whole sudoku set of numbers that are correct in order to solve the sudoku, widely used on the real-time based check system.
     *
     * <p>Key: {@code "Row,column"} — Value: Correct number (1–6).
     * Used to generate the random solutions and helps</p>
     */
    private Map<String, Integer> solution;

    /**
     * Cset of cells that can´t be edited by the player.
     *
     * <p>a key present in this set, indicates that the cell represented by the mentioned key was generated by the game, whether its a presolved number cell, or a help asked by the user.</p>
     */
    private Set<String> fixedCells;

    /** Random number generator. */
    private Random random;

    /**
     * new game with a new 6x6 sudoku board.
     */
    public SudokuBoard() {
        board = new HashMap<>();
        solution = new HashMap<>();
        fixedCells = new HashSet<>();
        random = new Random();
        generateNewGame();
    }

    // -------------------------------------------------------
    // Game generation
    // -------------------------------------------------------

    /**
     * 
     *
     * <p>Cleans both the hashmaps and hashsets, generates a new solution and set of uneditable cells, two for each 2x3 block.</p>
     */
    public void generateNewGame() {
        board.clear();
        solution.clear();
        fixedCells.clear();
        generateSolution(0, 0);
        generateInitialNumbers();
    }

    /**
     * Generates a new solution using backtracing
     *
     * <p>tries numbers from 1 to 6 in each cell, if any number passes the rules, it goes back.</p>
     *
     * @param row   actual proccesed row
     * @param column actual proccesed cell
     * @return {@code true} if solution was succesfully generated
     */
    private boolean generateSolution(int row, int column) {
        if (row == SIZE) return true;

        int nextRow = row;
        int nextCol = column + 1;
        if (nextCol == SIZE) {
            nextCol = 0;
            nextRow++;
        }

        int[] numbers = createShuffledNumbers();

        for (int number : numbers) {
            if (canPlaceInMap(solution, row, column, number)) {
                solution.put(key(row, column), number);

                if (generateSolution(nextRow, nextCol)) return true;

                solution.remove(key(row, column));
            }
        }

        return false;
    }

    /**
     * CReates an arregement from 1-6 using fisher yates algorithm (basically this algoritm takes the last element form the arrangment, chooses a random partner, the taken element included, to swap positions with, it does it till it reaches the first element of the arrangment).
     *
     * @return arrangment mixed with numbers from 1 to 6
     */
    private int[] createShuffledNumbers() {
        int[] numbers = {1, 2, 3, 4, 5, 6};

        for (int i = SIZE - 1; i > 0; i--) {
            int j = random.nextInt(i + 1);
            int temp = numbers[i];
            numbers[i] = numbers[j];
            numbers[j] = temp;
        }

        return numbers;
    }

    /**
     * generates initial fixed numbers 
     *
     * <p>selects to cells on each 2x3 block, uses the solution hashmap to give it a value and saves it as uneditable on {@code fixedCells}.</p>
     */
    private void generateInitialNumbers() {
        for (int blockRow = 0; blockRow < SIZE; blockRow += BLOCK_ROWS) {
            for (int blockCol = 0; blockCol < SIZE; blockCol += BLOCK_COLS) {

                int[][] positions = new int[BLOCK_ROWS * BLOCK_COLS][2];
                int index = 0;

                for (int row = blockRow; row < blockRow + BLOCK_ROWS; row++) {
                    for (int col = blockCol; col < blockCol + BLOCK_COLS; col++) {
                        positions[index][0] = row;
                        positions[index][1] = col;
                        index++;
                    }
                }

                shufflePositions(positions);

                for (int i = 0; i < 2; i++) {
                    int row = positions[i][0];
                    int col = positions[i][1];
                    String k = key(row, col);

                    board.put(k, solution.get(k));
                    fixedCells.add(k);
                }
            }
        }
    }

    /**
     * mixes and arrangment of positions on {@code [fila, columna]} using Fisher-Yates.
     *
     * @param positions arrangment of mixed positions
     */
    private void shufflePositions(int[][] positions) {
        for (int i = positions.length - 1; i > 0; i--) {
            int j = random.nextInt(i + 1);
            int[] temp = positions[i];
            positions[i] = positions[j];
            positions[j] = temp;
        }
    }

    // -------------------------------------------------------
    // Validación
    // -------------------------------------------------------

    /**
     * Verifica si un número puede colocarse en una celda de un mapa dado.
     *
     * <p>Valida las tres reglas del Sudoku:</p>
     * <ul>
     *     <li>El número no debe existir en la misma fila.</li>
     *     <li>El número no debe existir en la misma columna.</li>
     *     <li>El número no debe existir en el mismo bloque 2×3.</li>
     * </ul>
     *
     * @param map    el mapa donde se verificará el número
     * @param row    fila donde se colocará el número
     * @param column columna donde se colocará el número
     * @param number número a validar
     * @return {@code true} si el número puede colocarse
     */
    public boolean canPlaceInMap(Map<String, Integer> map, int row, int column, int number) {
        if (!isValidPosition(row, column)) return false;
        if (!isValidNumber(number)) return false;

        // Validar fila
        for (int col = 0; col < SIZE; col++) {
            if (map.getOrDefault(key(row, col), 0) == number) return false;
        }

        // Validar columna
        for (int r = 0; r < SIZE; r++) {
            if (map.getOrDefault(key(r, column), 0) == number) return false;
        }

        // Validar bloque 2×3
        int startRow = (row / BLOCK_ROWS) * BLOCK_ROWS;
        int startCol = (column / BLOCK_COLS) * BLOCK_COLS;

        for (int r = startRow; r < startRow + BLOCK_ROWS; r++) {
            for (int c = startCol; c < startCol + BLOCK_COLS; c++) {
                if (map.getOrDefault(key(r, c), 0) == number) return false;
            }
        }

        return true;
    }

    /**
     * Verifica si el usuario puede colocar un número en una celda específica.
     *
     * <p>El valor actual de la celda se elimina temporalmente del mapa antes
     * de la validación, permitiendo reemplazar un valor ya ingresado.</p>
     *
     * @param row    fila donde el usuario desea colocar el número
     * @param column columna donde el usuario desea colocar el número
     * @param number número que el usuario desea colocar
     * @return {@code true} si el movimiento es válido
     */
    public boolean verifyMove(int row, int column, int number) {
        if (!isValidPosition(row, column)) return false;
        if (!isValidNumber(number)) return false;
        if (isFixedCell(row, column)) return false;

        String k = key(row, column);
        Integer current = board.remove(k); // eliminar temporalmente

        boolean valid = canPlaceInMap(board, row, column, number);

        if (current != null) board.put(k, current); // restaurar

        return valid;
    }

    /**
     * Coloca un número en el tablero si el movimiento es válido.
     *
     * <p>Llama internamente a {@link #verifyMove(int, int, int)}.
     * Si el movimiento es válido, el número se agrega al mapa {@code board}.</p>
     *
     * @param row    fila donde se colocará el número
     * @param column columna donde se colocará el número
     * @param number número a colocar
     * @return {@code true} si el número fue colocado
     */
    public boolean placeNumber(int row, int column, int number) {
        if (!verifyMove(row, column, number)) return false;
        board.put(key(row, column), number);
        return true;
    }

    /**
     * Limpia una celda no fija eliminando su entrada del mapa {@code board}.
     *
     * @param row    fila de la celda a limpiar
     * @param column columna de la celda a limpiar
     * @return {@code true} si la celda fue limpiada
     */
    public boolean clearCell(int row, int column) {
        if (!isValidPosition(row, column)) return false;
        if (isFixedCell(row, column)) return false;
        board.remove(key(row, column));
        return true;
    }

    // -------------------------------------------------------
    // Estado del juego
    // -------------------------------------------------------

    /**
     * Verifica si el tablero está completo.
     *
     * <p>El tablero está completo cuando el mapa {@code board} contiene
     * exactamente 36 entradas (6×6).</p>
     *
     * @return {@code true} si todas las celdas tienen un valor
     */
    public boolean isComplete() {
        return board.size() == SIZE * SIZE;
    }

    /**
     * Verifica si el estado actual del tablero es válido según las reglas del Sudoku.
     *
     * <p>Cada valor se elimina temporalmente del mapa antes de validarlo
     * para evitar que la celda se detecte a sí misma como duplicado.</p>
     *
     * @return {@code true} si el tablero es válido
     */
    public boolean isBoardValid() {
        for (Map.Entry<String, Integer> entry : board.entrySet()) {
            String k = entry.getKey();
            int number = entry.getValue();
            int[] pos = parseKey(k);

            board.remove(k);
            boolean valid = canPlaceInMap(board, pos[0], pos[1], number);
            board.put(k, number);

            if (!valid) return false;
        }
        return true;
    }

    /**
     * Verifica si el juego ha sido ganado (tablero completo y válido).
     *
     * @return {@code true} si el juego fue ganado
     */
    public boolean isGameWon() {
        return isComplete() && isBoardValid();
    }

    // -------------------------------------------------------
    // Getters
    // -------------------------------------------------------

    /**
     * Retorna el valor actual de una celda, o {@code 0} si está vacía.
     *
     * @param row    fila de la celda
     * @param column columna de la celda
     * @return valor almacenado, {@code 0} si vacía, {@code -1} si posición inválida
     */
    public int getValue(int row, int column) {
        if (!isValidPosition(row, column)) return -1;
        return board.getOrDefault(key(row, column), 0);
    }

    /**
     * Retorna el valor de la solución en una celda específica.
     *
     * @param row    fila de la celda
     * @param column columna de la celda
     * @return valor de la solución, o {@code -1} si la posición es inválida
     */
    public int getSolutionValue(int row, int column) {
        if (!isValidPosition(row, column)) return -1;
        return solution.getOrDefault(key(row, column), -1);
    }

    /**
     * Verifica si una celda es fija (no editable por el usuario).
     *
     * @param row    fila de la celda
     * @param column columna de la celda
     * @return {@code true} si la celda es fija
     */
    public boolean isFixedCell(int row, int column) {
        if (!isValidPosition(row, column)) return false;
        return fixedCells.contains(key(row, column));
    }

    /**
     * Verifica si una posición es válida dentro del tablero.
     *
     * @param row    fila a validar
     * @param column columna a validar
     * @return {@code true} si la posición está dentro del tablero
     */
    public boolean isValidPosition(int row, int column) {
        return row >= 0 && row < SIZE && column >= 0 && column < SIZE;
    }

    /**
     * Verifica si un número es válido para un Sudoku 6x6.
     *
     * @param number número a validar
     * @return {@code true} si el número está entre 1 y 6
     */
    public boolean isValidNumber(int number) {
        return number >= 1 && number <= SIZE;
    }

    /**
     * Retorna una copia del mapa del tablero actual.
     *
     * @return copia del tablero como {@link Map}
     */
    public Map<String, Integer> getBoard() {
        return new HashMap<>(board);
    }

    /**
     * Retorna una copia del conjunto de celdas fijas.
     *
     * @return copia del conjunto de claves fijas como {@link Set}
     */
    public Set<String> getFixedCells() {
        return new HashSet<>(fixedCells);
    }

    // -------------------------------------------------------
    // Utilidades internas
    // -------------------------------------------------------

    /**
     * Genera la clave {@code "fila,columna"} usada como identificador en los mapas.
     *
     * @param row    fila
     * @param column columna
     * @return cadena con formato {@code "fila,columna"}
     */
    private String key(int row, int column) {
        return row + "," + column;
    }

    /**
     * Parsea una clave {@code "fila,columna"} y retorna {@code [fila, columna]}.
     *
     * @param key clave a parsear
     * @return arreglo de dos enteros: {@code [fila, columna]}
     */
    private int[] parseKey(String key) {
        String[] parts = key.split(",");
        return new int[]{Integer.parseInt(parts[0]), Integer.parseInt(parts[1])};
    }

    /**
     * Imprime el estado actual del tablero en la consola.
     * Útil para depuración durante el desarrollo.
     */
    public void showBoard() {
        for (int row = 0; row < SIZE; row++) {
            for (int col = 0; col < SIZE; col++) {
                System.out.print(board.getOrDefault(key(row, col), 0) + " ");
            }
            System.out.println();
        }
        System.out.println();
    }
}
